import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { VehicleCard } from "../components/VehicleCard";
import { useNotification } from "../context/NotificationContext";
import {
	Car,
	Loader2,
	ChevronLeft,
	ChevronRight,
	Filter,
	X,
	Search as SearchIcon,
	FileDown,
	FileSpreadsheet,
} from "lucide-react";
import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";
import * as XLSX from "xlsx";

const PAGE_SIZE = 12;

function getPageNumbers(current, total) {
	if (total <= 5) return Array.from({ length: total }, (_, i) => i + 1);
	const pages = [];
	if (current <= 3) {
		pages.push(1, 2, 3, 4, "...", total);
	} else if (current >= total - 2) {
		pages.push(1, "...", total - 3, total - 2, total - 1, total);
	} else {
		pages.push(1, "...", current - 1, current, current + 1, "...", total);
	}
	return [...new Set(pages)];
}

const HEADER_TEXT =
	"Generated by Smart Vehicle Inventory Manager by Asahi Motors";

function vehicleToRow(v) {
	return [
		v.stock_id || "",
		v.plate_no || "",
		v.brand || "",
		v.model || "",
		v.body || "",
		v.color || "",
		v.mileage ?? "",
		v.cc ?? "",
		v.model_year ?? "",
		v.fuel_type || "",
		v.gear || "",
		v.location || "",
		v.sold ? "Yes" : "No",
		v.reserved ? "Yes" : "No",
	];
}

const EXPORT_COLUMNS = [
	"Stock ID",
	"Plate No",
	"Brand",
	"Model",
	"Body",
	"Color",
	"Mileage",
	"CC",
	"Model Year",
	"Fuel",
	"Gear",
	"Location",
	"Sold",
	"Reserved",
];

export function VehicleList() {
	const [vehicles, setVehicles] = useState([]);
	const [loading, setLoading] = useState(true);
	const [availableBrands, setAvailableBrands] = useState([]);
	const [brandsLoading, setBrandsLoading] = useState(true);
	const [page, setPage] = useState(1);
	const [totalCount, setTotalCount] = useState(0);
	const [filterOpen, setFilterOpen] = useState(false);
	const [searchQuery, setSearchQuery] = useState("");
	const [brandFilter, setBrandFilter] = useState("");
	const [modelFilter, setModelFilter] = useState("");
	const [statusFilter, setStatusFilter] = useState("");
	const [maxPriceInput, setMaxPriceInput] = useState("");
	const [models, setModels] = useState([]);
	const [modelCounts, setModelCounts] = useState({});
	const [exporting, setExporting] = useState(false);
	const { addNotification } = useNotification();

	useEffect(() => {
		async function fetchBrands() {
			setBrandsLoading(true);
			try {
				const { data, error } = await supabase
					.from("vehicles")
					.select("brand")
					.not("brand", "is", null);
				if (error) throw error;
				const brands = [...new Set((data || []).map((r) => r.brand).filter(Boolean))].sort();
				setAvailableBrands(brands);
			} catch (err) {
				addNotification(err.message || "Failed to load brands", "error");
			} finally {
				setBrandsLoading(false);
			}
		}
		fetchBrands();
	}, []);

	useEffect(() => {
		if (!brandFilter) {
			setModels([]);
			setModelFilter("");
			return;
		}
		supabase
			.from("vehicles")
			.select("model")
			.ilike("brand", brandFilter)
			.then(({ data }) => {
				const unique = [
					...new Set((data || []).map((r) => r.model).filter(Boolean)),
				].sort();
				setModels(unique);
				setModelFilter("");
			});
	}, [brandFilter]);

	useEffect(() => {
		fetchVehicles();
	}, [page, searchQuery, brandFilter, modelFilter, statusFilter, maxPriceInput]);

	useEffect(() => {
		fetchModelCounts();
	}, [searchQuery, brandFilter, modelFilter, statusFilter, maxPriceInput]);

	async function fetchModelCounts() {
		try {
			let qb = supabase.from("vehicles").select("brand, model");
			if (statusFilter === "available") qb = qb.eq("sold", false).eq("reserved", false);
			if (statusFilter === "sold") qb = qb.eq("sold", true);
			if (statusFilter === "reserved") qb = qb.eq("reserved", true).neq("sold", true);
			if (searchQuery.trim()) {
				qb = qb.or(
					`stock_id.ilike.%${searchQuery.trim()}%,plate_no.ilike.%${searchQuery.trim()}%,brand.ilike.%${searchQuery.trim()}%,model.ilike.%${searchQuery.trim()}%,location.ilike.%${searchQuery.trim()}%`
				);
			}
			if (brandFilter) qb = qb.ilike("brand", brandFilter);
			if (modelFilter) qb = qb.ilike("model", modelFilter);
			const maxPrice = maxPriceInput.trim() ? parseFloat(maxPriceInput) : null;
			if (maxPrice != null && !isNaN(maxPrice) && maxPrice > 0) qb = qb.lte("selling_price", maxPrice);
			const { data } = await qb.limit(2000);
			const counts = {};
			(data || []).forEach((v) => {
				const key = `${(v.brand || "").trim()}|${(v.model || "").trim()}`;
				counts[key] = (counts[key] || 0) + 1;
			});
			setModelCounts(counts);
		} catch {
			setModelCounts({});
		}
	}

	async function fetchVehicles() {
		setLoading(true);
		try {
			let qb = supabase
				.from("vehicles")
				.select(
					`
          *,
          vehicle_images (
            id,
            storage_path,
            sort_order
          )
        `,
					{ count: "exact" },
				)
				.order("created_at", { ascending: false });

			if (statusFilter === "available")
				qb = qb.eq("sold", false).eq("reserved", false);
			if (statusFilter === "sold") qb = qb.eq("sold", true);
			if (statusFilter === "reserved") qb = qb.eq("reserved", true).neq("sold", true);

			if (searchQuery.trim()) {
				qb = qb.or(
					`stock_id.ilike.%${searchQuery.trim()}%,plate_no.ilike.%${searchQuery.trim()}%,brand.ilike.%${searchQuery.trim()}%,model.ilike.%${searchQuery.trim()}%,location.ilike.%${searchQuery.trim()}%`,
				);
			}
			if (brandFilter) qb = qb.ilike("brand", brandFilter);
			if (modelFilter) qb = qb.ilike("model", modelFilter);
			const maxPrice = maxPriceInput.trim() ? parseFloat(maxPriceInput) : null;
			if (maxPrice != null && !isNaN(maxPrice) && maxPrice > 0) qb = qb.lte("selling_price", maxPrice);

			const from = (page - 1) * PAGE_SIZE;
			const to = from + PAGE_SIZE - 1;
			const { data, error, count } = await qb.range(from, to);

			if (error) throw error;

			const withUrls = (data || []).map((v) => {
				const images = (v.vehicle_images || []).map((img) => ({
					...img,
					url: supabase.storage
						.from("vehicle-images")
						.getPublicUrl(img.storage_path).data.publicUrl,
				}));
				return { ...v, images };
			});

			setVehicles(withUrls);
			setTotalCount(count ?? 0);
		} catch (err) {
			addNotification(err.message || "Failed to load vehicles", "error");
		} finally {
			setLoading(false);
		}
	}

	async function fetchAllFiltered() {
		let qb = supabase
			.from("vehicles")
			.select("*")
			.order("created_at", { ascending: false });

		if (statusFilter === "available") qb = qb.eq("sold", false).eq("reserved", false);
		if (statusFilter === "sold") qb = qb.eq("sold", true);
		if (statusFilter === "reserved") qb = qb.eq("reserved", true).neq("sold", true);

		if (searchQuery.trim()) {
			qb = qb.or(
				`stock_id.ilike.%${searchQuery.trim()}%,plate_no.ilike.%${searchQuery.trim()}%,brand.ilike.%${searchQuery.trim()}%,model.ilike.%${searchQuery.trim()}%,location.ilike.%${searchQuery.trim()}%`,
			);
		}
		if (brandFilter) qb = qb.ilike("brand", brandFilter);
		if (modelFilter) qb = qb.ilike("model", modelFilter);
		const maxPrice = maxPriceInput.trim() ? parseFloat(maxPriceInput) : null;
		if (maxPrice != null && !isNaN(maxPrice) && maxPrice > 0) qb = qb.lte("selling_price", maxPrice);

		const { data, error } = await qb.limit(5000);
		if (error) throw error;
		return data || [];
	}

	function exportPDF() {
		setExporting(true);
		fetchAllFiltered()
			.then((rows) => {
				const doc = new jsPDF({ orientation: "landscape" });
				const now = new Date();
				const dateStr = now.toLocaleDateString("en-GB", {
					day: "2-digit",
					month: "short",
					year: "numeric",
				});
				const timeStr = now.toLocaleTimeString("en-GB", {
					hour: "2-digit",
					minute: "2-digit",
					second: "2-digit",
				});

				doc.setFontSize(11);
				doc.setFont(undefined, "bold");
				doc.text(HEADER_TEXT, 14, 10);
				doc.setFont(undefined, "normal");
				doc.setFontSize(9);
				doc.text(`Date: ${dateStr}  |  Time: ${timeStr}`, 14, 16);

				autoTable(doc, {
					head: [EXPORT_COLUMNS],
					body: rows.map(vehicleToRow),
					startY: 22,
					styles: { fontSize: 8 },
					headStyles: { fillColor: [245, 158, 11] },
					didDrawPage: (data) => {
						if (data.pageNumber > 1) {
							doc.setFontSize(8);
							doc.text(HEADER_TEXT + ` | ${dateStr} ${timeStr}`, 14, 10);
						}
					},
				});

				doc.save(`vehicle-inventory-${now.toISOString().slice(0, 10)}.pdf`);
				addNotification("PDF exported", "success");
			})
			.catch((err) => addNotification(err.message || "Export failed", "error"))
			.finally(() => setExporting(false));
	}

	function exportExcel() {
		setExporting(true);
		fetchAllFiltered()
			.then((rows) => {
				const wsData = [EXPORT_COLUMNS, ...rows.map(vehicleToRow)];
				const ws = XLSX.utils.aoa_to_sheet(wsData);
				const wb = XLSX.utils.book_new();
				XLSX.utils.book_append_sheet(wb, ws, "Inventory");

				const now = new Date();
				XLSX.writeFile(
					wb,
					`vehicle-inventory-${now.toISOString().slice(0, 10)}.xlsx`,
				);
				addNotification("Excel exported", "success");
			})
			.catch((err) => addNotification(err.message || "Export failed", "error"))
			.finally(() => setExporting(false));
	}

	const totalPages = Math.ceil(totalCount / PAGE_SIZE) || 1;
	const hasPrev = page > 1;
	const hasNext = page < totalPages;
	const hasActiveFilters = searchQuery || brandFilter || modelFilter || statusFilter || maxPriceInput.trim();

	const applyFilters = () => {
		setPage(1);
		setFilterOpen(false);
	};

	const clearFilters = () => {
		setSearchQuery("");
		setBrandFilter("");
		setModelFilter("");
		setStatusFilter("");
		setMaxPriceInput("");
		setPage(1);
	};

	const getModelCount = (v) => {
		const key = `${(v.brand || "").trim()}|${(v.model || "").trim()}`;
		return modelCounts[key] || 1;
	};

	return (
		<div className="min-h-full">
			<div className="flex justify-between items-start mb-8">
				<div>
					<p className="text-xs font-medium text-amber-500/80 uppercase tracking-widest mb-1">
						Inventory
					</p>
					<h1 className="text-2xl md:text-3xl font-bold text-white tracking-tight">
						Vehicle Stock
					</h1>
					<p className="text-zinc-500 text-sm mt-1.5">
						Browse and manage your fleet
					</p>
				</div>
				<button
					type="button"
					onClick={() => setFilterOpen(true)}
					className={`p-3 rounded-xl border transition-all ${
						hasActiveFilters
							? "bg-amber-500/10 border-amber-500/40 text-amber-400"
							: "bg-zinc-800/50 border-zinc-700/80 text-zinc-400 hover:text-white hover:border-zinc-600"
					}`}
					aria-label="Filter"
				>
					<Filter className="w-5 h-5" />
				</button>
			</div>

			<div className="mb-4 flex items-center gap-4">
				<div>
					<label className="block text-xs text-zinc-500 mb-1">Max price (£)</label>
					<input
						type="number"
						min="0"
						step="100"
						value={maxPriceInput}
						onChange={(e) => {
							setMaxPriceInput(e.target.value);
							setPage(1);
						}}
						placeholder="e.g. 10000"
						className="w-32 px-4 py-2.5 rounded-lg bg-zinc-800/80 border border-zinc-700/80 text-white placeholder-zinc-500 focus:ring-2 focus:ring-amber-500/40"
					/>
				</div>
			</div>

			<div className="flex gap-2 mb-8 overflow-x-auto pb-2 scrollbar-hide">
				<button
					onClick={() => {
						setBrandFilter("");
						setPage(1);
					}}
					className={`px-5 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap transition-all duration-200 ${
						!brandFilter
							? "bg-amber-500/15 border border-amber-500/40 text-amber-400 shadow-sm shadow-amber-500/5"
							: "bg-zinc-800/40 border border-zinc-700/60 text-zinc-400 hover:text-zinc-200 hover:border-zinc-600 hover:bg-zinc-800/60"
					}`}
				>
					All
				</button>
				{brandsLoading ? (
					<div className="flex items-center gap-2 px-4 py-2.5 text-zinc-500 text-sm">
						<Loader2 className="w-4 h-4 animate-spin" />
						Makes...
					</div>
				) : (
					availableBrands.map((brand) => (
						<button
							key={brand}
							onClick={() => {
								setBrandFilter(brand);
								setPage(1);
							}}
							className={`px-5 py-2.5 rounded-xl text-sm font-medium whitespace-nowrap transition-all duration-200 ${
								brandFilter === brand
									? "bg-amber-500/15 border border-amber-500/40 text-amber-400 shadow-sm shadow-amber-500/5"
									: "bg-zinc-800/40 border border-zinc-700/60 text-zinc-400 hover:text-zinc-200 hover:border-zinc-600 hover:bg-zinc-800/60"
							}`}
						>
							{brand}
						</button>
					))
				)}
			</div>

			{loading ? (
				<div className="flex flex-col items-center justify-center py-28">
					<Loader2 className="w-10 h-10 text-amber-500/80 animate-spin mb-4" />
					<p className="text-zinc-500 text-sm font-medium">
						Loading inventory...
					</p>
				</div>
			) : vehicles.length === 0 ? (
				<div className="text-center py-28 rounded-2xl border border-zinc-800/50 bg-zinc-900/40">
					<div className="w-20 h-20 mx-auto mb-5 rounded-2xl bg-zinc-800/60 flex items-center justify-center">
						<Car className="w-10 h-10 text-zinc-600" />
					</div>
					<p className="text-zinc-300 font-semibold">No vehicles found</p>
					<p className="text-zinc-500 text-sm mt-1.5">
						Adjust filters or add a new vehicle
					</p>
				</div>
			) : (
				<>
					<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
					{vehicles.map((v) => (
						<VehicleCard key={v.id} vehicle={v} modelCount={getModelCount(v)} />
					))}
					</div>

					{totalPages > 1 && (
						<div className="flex flex-col sm:flex-row items-center justify-between gap-4 mt-10 py-5 px-2">
							<div className="flex items-center gap-2">
								<button
									type="button"
									onClick={() => setPage((p) => Math.max(1, p - 1))}
									disabled={!hasPrev}
									className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-zinc-800/60 border border-zinc-700/60 text-zinc-300 hover:bg-zinc-700/60 disabled:opacity-40 disabled:cursor-not-allowed transition"
								>
									<ChevronLeft className="w-4 h-4" />
									Prev
								</button>
								<div className="flex items-center gap-1">
									{getPageNumbers(page, totalPages).map((p, i) =>
										p === "..." ? (
											<span key={`ellipsis-${i}`} className="px-2 text-zinc-500">
												…
											</span>
										) : (
											<button
												key={p}
												type="button"
												onClick={() => setPage(p)}
												className={`min-w-[2.25rem] h-9 px-2.5 rounded-lg text-sm font-medium transition ${
													page === p
														? "bg-amber-500/20 border border-amber-500/40 text-amber-400"
														: "bg-zinc-800/60 border border-zinc-700/60 text-zinc-400 hover:text-white hover:border-zinc-600"
												}`}
											>
												{p}
											</button>
										)
									)}
								</div>
								<button
									type="button"
									onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
									disabled={!hasNext}
									className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-zinc-800/60 border border-zinc-700/60 text-zinc-300 hover:bg-zinc-700/60 disabled:opacity-40 disabled:cursor-not-allowed transition"
								>
									Next
									<ChevronRight className="w-4 h-4" />
								</button>
							</div>
							<span className="text-zinc-500 text-sm font-medium">
								{totalCount} vehicle{totalCount !== 1 ? "s" : ""} · Page {page} of {totalPages}
							</span>
						</div>
					)}
				</>
			)}

			{filterOpen && (
				<div
					className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4"
					onClick={() => setFilterOpen(false)}
				>
					<div
						className="bg-zinc-900 rounded-2xl border border-zinc-700/80 shadow-2xl w-full max-w-md max-h-[90vh] overflow-y-auto"
						onClick={(e) => e.stopPropagation()}
					>
						<div className="flex justify-between items-center p-5 border-b border-zinc-700/80">
							<h3 className="text-lg font-semibold text-white tracking-tight">
								Filter & Export
							</h3>
							<button
								type="button"
								onClick={() => setFilterOpen(false)}
								className="p-2 rounded-lg hover:bg-zinc-800 text-zinc-400 transition"
								aria-label="Close"
							>
								<X className="w-5 h-5" />
							</button>
						</div>

						<div className="p-5 space-y-4">
							<div>
								<label className="block text-xs font-medium text-zinc-500 uppercase tracking-wider mb-2">
									Search
								</label>
								<div className="relative">
									<SearchIcon className="absolute left-3.5 top-1/2 -translate-y-1/2 w-5 h-5 text-zinc-500" />
									<input
										type="text"
										value={searchQuery}
										onChange={(e) => setSearchQuery(e.target.value)}
										placeholder="Stock ID, plate, brand, model..."
										className="w-full pl-11 pr-4 py-3 rounded-xl bg-zinc-800/80 border border-zinc-700/80 text-white placeholder-zinc-500 focus:ring-2 focus:ring-amber-500/40 focus:border-amber-500/40 transition"
									/>
								</div>
							</div>

							<div className="grid grid-cols-2 gap-3">
								<div>
									<label className="block text-xs font-medium text-zinc-500 uppercase tracking-wider mb-2">
										Brand
									</label>
									<select
										value={brandFilter}
										onChange={(e) => setBrandFilter(e.target.value)}
										className="w-full px-4 py-3 rounded-xl bg-zinc-800/80 border border-zinc-700/80 text-white focus:ring-2 focus:ring-amber-500/40"
									>
										<option value="">All brands</option>
										{availableBrands.map((b) => (
											<option key={b} value={b}>
												{b}
											</option>
										))}
									</select>
								</div>
								<div>
									<label className="block text-xs font-medium text-zinc-500 uppercase tracking-wider mb-2">
										Model
									</label>
									<select
										value={modelFilter}
										onChange={(e) => setModelFilter(e.target.value)}
										className="w-full px-4 py-3 rounded-xl bg-zinc-800/80 border border-zinc-700/80 text-white focus:ring-2 focus:ring-amber-500/40"
									>
										<option value="">All models</option>
										{models.map((m) => (
											<option key={m} value={m}>
												{m}
											</option>
										))}
									</select>
								</div>
							</div>

							<div>
								<label className="block text-xs font-medium text-zinc-500 uppercase tracking-wider mb-2">
									Max price (£)
								</label>
								<input
									type="number"
									min="0"
									step="100"
									value={maxPriceInput}
									onChange={(e) => setMaxPriceInput(e.target.value)}
									placeholder="e.g. 10000"
									className="w-full px-4 py-3 rounded-xl bg-zinc-800/80 border border-zinc-700/80 text-white placeholder-zinc-500 focus:ring-2 focus:ring-amber-500/40"
								/>
							</div>

							<div>
								<label className="block text-xs font-medium text-zinc-500 uppercase tracking-wider mb-2">
									Status
								</label>
								<select
									value={statusFilter}
									onChange={(e) => setStatusFilter(e.target.value)}
									className="w-full px-4 py-3 rounded-xl bg-zinc-800/80 border border-zinc-700/80 text-white focus:ring-2 focus:ring-amber-500/40"
								>
									<option value="">All status</option>
									<option value="available">Available</option>
									<option value="sold">Sold</option>
									<option value="reserved">Reserved</option>
								</select>
							</div>

							{(searchQuery || brandFilter || modelFilter || statusFilter || maxPriceInput.trim()) && (
								<button
									type="button"
									onClick={clearFilters}
									className="text-sm text-amber-400 hover:text-amber-300 transition"
								>
									Clear filters
								</button>
							)}

							<div className="pt-4 border-t border-zinc-700/80">
								<p className="text-xs font-medium text-zinc-500 uppercase tracking-wider mb-3">
									Export
								</p>
								<div className="flex gap-3">
									<button
										type="button"
										onClick={exportPDF}
										disabled={exporting}
										className="flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-rose-600/90 hover:bg-rose-500 text-white disabled:opacity-50 transition"
									>
										<FileDown className="w-5 h-5" />
										PDF
									</button>
									<button
										type="button"
										onClick={exportExcel}
										disabled={exporting}
										className="flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-emerald-600/90 hover:bg-emerald-500 text-white disabled:opacity-50 transition"
									>
										<FileSpreadsheet className="w-5 h-5" />
										Excel
									</button>
								</div>
								<p className="text-xs text-zinc-600 mt-2">
									Exports all matching vehicles
								</p>
							</div>
						</div>

						<div className="p-5 border-t border-zinc-700/80">
							<button
								type="button"
								onClick={applyFilters}
								className="w-full py-3.5 rounded-xl bg-amber-500 hover:bg-amber-600 text-zinc-950 font-semibold transition"
							>
								Apply Filters
							</button>
						</div>
					</div>
				</div>
			)}
		</div>
	);
}
