import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { VehicleCard } from '../components/VehicleCard'
import { useNotification } from '../context/NotificationContext'
import { Car, Loader2, ChevronLeft, ChevronRight, Filter, X, Search as SearchIcon, FileDown, FileSpreadsheet } from 'lucide-react'
import { jsPDF } from 'jspdf'
import { autoTable } from 'jspdf-autotable'
import * as XLSX from 'xlsx'

const PAGE_SIZE = 12
const BRANDS = ['Audi', 'BMW', 'Fiat', 'Honda', 'Kia', 'Lexus', 'Mazda', 'Mercedes-Benz', 'Nissan', 'Toyota']

const HEADER_TEXT = 'Generated by Smart Vehicle Inventory Manager by Asahi Motors'

function vehicleToRow(v) {
  return [
    v.stock_id || '',
    v.plate_no || '',
    v.brand || '',
    v.model || '',
    v.body || '',
    v.color || '',
    v.mileage ?? '',
    v.cc ?? '',
    v.model_year ?? '',
    v.fuel_type || '',
    v.gear || '',
    v.location || '',
    v.sold ? 'Yes' : 'No',
    v.reserved ? 'Yes' : 'No',
  ]
}

const EXPORT_COLUMNS = [
  'Stock ID',
  'Plate No',
  'Brand',
  'Model',
  'Body',
  'Color',
  'Mileage',
  'CC',
  'Model Year',
  'Fuel',
  'Gear',
  'Location',
  'Sold',
  'Reserved',
]

export function VehicleList() {
  const [vehicles, setVehicles] = useState([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState('all')
  const [page, setPage] = useState(1)
  const [totalCount, setTotalCount] = useState(0)
  const [filterOpen, setFilterOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [brandFilter, setBrandFilter] = useState('')
  const [modelFilter, setModelFilter] = useState('')
  const [models, setModels] = useState([])
  const [exporting, setExporting] = useState(false)
  const { addNotification } = useNotification()

  useEffect(() => {
    if (!brandFilter) {
      setModels([])
      setModelFilter('')
      return
    }
    supabase
      .from('vehicles')
      .select('model')
      .ilike('brand', brandFilter)
      .then(({ data }) => {
        const unique = [...new Set((data || []).map((r) => r.model).filter(Boolean))].sort()
        setModels(unique)
        setModelFilter('')
      })
  }, [brandFilter])

  useEffect(() => {
    fetchVehicles()
  }, [filter, page, searchQuery, brandFilter, modelFilter])

  async function fetchVehicles() {
    setLoading(true)
    try {
      let qb = supabase
        .from('vehicles')
        .select(
          `
          *,
          vehicle_images (
            id,
            storage_path,
            sort_order
          )
        `,
          { count: 'exact' }
        )
        .order('created_at', { ascending: false })

      if (filter === 'available') qb = qb.eq('sold', false).eq('reserved', false)
      if (filter === 'sold') qb = qb.eq('sold', true)
      if (filter === 'reserved') qb = qb.eq('reserved', true).neq('sold', true)

      if (searchQuery.trim()) {
        qb = qb.or(
          `stock_id.ilike.%${searchQuery.trim()}%,plate_no.ilike.%${searchQuery.trim()}%,brand.ilike.%${searchQuery.trim()}%,model.ilike.%${searchQuery.trim()}%,location.ilike.%${searchQuery.trim()}%`
        )
      }
      if (brandFilter) qb = qb.ilike('brand', brandFilter)
      if (modelFilter) qb = qb.ilike('model', modelFilter)

      const from = (page - 1) * PAGE_SIZE
      const to = from + PAGE_SIZE - 1
      const { data, error, count } = await qb.range(from, to)

      if (error) throw error

      const withUrls = (data || []).map((v) => {
        const images = (v.vehicle_images || []).map((img) => ({
          ...img,
          url: supabase.storage.from('vehicle-images').getPublicUrl(img.storage_path).data.publicUrl,
        }))
        return { ...v, images }
      })

      setVehicles(withUrls)
      setTotalCount(count ?? 0)
    } catch (err) {
      addNotification(err.message || 'Failed to load vehicles', 'error')
    } finally {
      setLoading(false)
    }
  }

  async function fetchAllFiltered() {
    let qb = supabase
      .from('vehicles')
      .select('*')
      .order('created_at', { ascending: false })

    if (filter === 'available') qb = qb.eq('sold', false).eq('reserved', false)
    if (filter === 'sold') qb = qb.eq('sold', true)
    if (filter === 'reserved') qb = qb.eq('reserved', true).neq('sold', true)

    if (searchQuery.trim()) {
      qb = qb.or(
        `stock_id.ilike.%${searchQuery.trim()}%,plate_no.ilike.%${searchQuery.trim()}%,brand.ilike.%${searchQuery.trim()}%,model.ilike.%${searchQuery.trim()}%,location.ilike.%${searchQuery.trim()}%`
      )
    }
    if (brandFilter) qb = qb.ilike('brand', brandFilter)
    if (modelFilter) qb = qb.ilike('model', modelFilter)

    const { data, error } = await qb.limit(5000)
    if (error) throw error
    return data || []
  }

  function exportPDF() {
    setExporting(true)
    fetchAllFiltered()
      .then((rows) => {
        const doc = new jsPDF({ orientation: 'landscape' })
        const now = new Date()
        const dateStr = now.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
        const timeStr = now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' })

        doc.setFontSize(11)
        doc.setFont(undefined, 'bold')
        doc.text(HEADER_TEXT, 14, 10)
        doc.setFont(undefined, 'normal')
        doc.setFontSize(9)
        doc.text(`Date: ${dateStr}  |  Time: ${timeStr}`, 14, 16)

        autoTable(doc, {
          head: [EXPORT_COLUMNS],
          body: rows.map(vehicleToRow),
          startY: 22,
          styles: { fontSize: 8 },
          headStyles: { fillColor: [249, 115, 22] },
          didDrawPage: (data) => {
            if (data.pageNumber > 1) {
              doc.setFontSize(8)
              doc.text(HEADER_TEXT + ` | ${dateStr} ${timeStr}`, 14, 10)
            }
          },
        })

        doc.save(`vehicle-inventory-${now.toISOString().slice(0, 10)}.pdf`)
        addNotification('PDF exported', 'success')
      })
      .catch((err) => addNotification(err.message || 'Export failed', 'error'))
      .finally(() => setExporting(false))
  }

  function exportExcel() {
    setExporting(true)
    fetchAllFiltered()
      .then((rows) => {
        const wsData = [EXPORT_COLUMNS, ...rows.map(vehicleToRow)]
        const ws = XLSX.utils.aoa_to_sheet(wsData)
        const wb = XLSX.utils.book_new()
        XLSX.utils.book_append_sheet(wb, ws, 'Inventory')

        const now = new Date()
        XLSX.writeFile(wb, `vehicle-inventory-${now.toISOString().slice(0, 10)}.xlsx`)
        addNotification('Excel exported', 'success')
      })
      .catch((err) => addNotification(err.message || 'Export failed', 'error'))
      .finally(() => setExporting(false))
  }

  const totalPages = Math.ceil(totalCount / PAGE_SIZE) || 1
  const hasPrev = page > 1
  const hasNext = page < totalPages
  const hasActiveFilters = searchQuery || brandFilter || modelFilter

  const applyFilters = () => {
    setPage(1)
    setFilterOpen(false)
  }

  const clearFilters = () => {
    setSearchQuery('')
    setBrandFilter('')
    setModelFilter('')
    setPage(1)
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-4">
        <h1 className="text-xl font-bold text-white flex items-center gap-2">
          <Car className="w-6 h-6 text-orange-500" />
          Vehicle Inventory
        </h1>
        <button
          type="button"
          onClick={() => setFilterOpen(true)}
          className={`p-2.5 rounded-xl border transition ${
            hasActiveFilters
              ? 'bg-orange-500/20 border-orange-500/50 text-orange-400'
              : 'bg-slate-800 border-slate-700 text-slate-400 hover:text-white'
          }`}
          aria-label="Filter"
        >
          <Filter className="w-5 h-5" />
        </button>
      </div>

      <div className="flex gap-2 mb-4 overflow-x-auto pb-2 -mx-4 px-4">
        {['all', 'available', 'sold', 'reserved'].map((f) => (
          <button
            key={f}
            onClick={() => { setFilter(f); setPage(1) }}
            className={`px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap transition ${
              filter === f
                ? 'bg-orange-500 text-white'
                : 'bg-slate-800 text-slate-400 hover:text-white'
            }`}
          >
            {f.charAt(0).toUpperCase() + f.slice(1)}
          </button>
        ))}
      </div>

      {loading ? (
        <div className="flex justify-center py-16">
          <Loader2 className="w-10 h-10 text-orange-500 animate-spin" />
        </div>
      ) : vehicles.length === 0 ? (
        <div className="text-center py-16 text-slate-400">
          <Car className="w-16 h-16 mx-auto mb-4 opacity-50" />
          <p>No vehicles found</p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {vehicles.map((v) => (
              <VehicleCard key={v.id} vehicle={v} />
            ))}
          </div>

          {totalPages > 1 && (
            <div className="flex items-center justify-between mt-6 py-4">
              <button
                type="button"
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                disabled={!hasPrev}
                className="flex items-center gap-1 px-4 py-2 rounded-lg bg-slate-800 text-slate-300 hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <ChevronLeft className="w-4 h-4" />
                Prev
              </button>
              <span className="text-slate-400 text-sm">
                Page {page} of {totalPages}
              </span>
              <button
                type="button"
                onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                disabled={!hasNext}
                className="flex items-center gap-1 px-4 py-2 rounded-lg bg-slate-800 text-slate-300 hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Next
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          )}
        </>
      )}

      {filterOpen && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4"
          onClick={() => setFilterOpen(false)}
        >
          <div
            className="bg-slate-800 rounded-2xl border border-slate-700 shadow-xl w-full max-w-md max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex justify-between items-center p-4 border-b border-slate-700">
              <h3 className="text-lg font-semibold text-white flex items-center gap-2">
                <Filter className="w-5 h-5 text-orange-500" />
                Filter & Export
              </h3>
              <button
                type="button"
                onClick={() => setFilterOpen(false)}
                className="p-2 rounded-lg hover:bg-slate-700 text-slate-400"
                aria-label="Close"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="p-4 space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-400 mb-1">Search</label>
                <div className="relative">
                  <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-500" />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Stock ID, plate, brand, model..."
                    className="w-full pl-10 pr-4 py-2.5 rounded-lg bg-slate-900 border border-slate-700 text-white placeholder-slate-500 focus:ring-2 focus:ring-orange-500"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-sm font-medium text-slate-400 mb-1">Brand</label>
                  <select
                    value={brandFilter}
                    onChange={(e) => setBrandFilter(e.target.value)}
                    className="w-full px-4 py-2.5 rounded-lg bg-slate-900 border border-slate-700 text-white focus:ring-2 focus:ring-orange-500"
                  >
                    <option value="">All brands</option>
                    {BRANDS.map((b) => (
                      <option key={b} value={b}>{b}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-400 mb-1">Model</label>
                  <select
                    value={modelFilter}
                    onChange={(e) => setModelFilter(e.target.value)}
                    className="w-full px-4 py-2.5 rounded-lg bg-slate-900 border border-slate-700 text-white focus:ring-2 focus:ring-orange-500"
                  >
                    <option value="">All models</option>
                    {models.map((m) => (
                      <option key={m} value={m}>{m}</option>
                    ))}
                  </select>
                </div>
              </div>

              {(searchQuery || brandFilter || modelFilter) && (
                <button
                  type="button"
                  onClick={clearFilters}
                  className="text-sm text-orange-400 hover:text-orange-300"
                >
                  Clear filters
                </button>
              )}

              <div className="pt-4 border-t border-slate-700">
                <p className="text-sm font-medium text-slate-400 mb-3">Export filtered data</p>
                <div className="flex gap-3">
                  <button
                    type="button"
                    onClick={exportPDF}
                    disabled={exporting}
                    className="flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-red-600 hover:bg-red-500 text-white disabled:opacity-50"
                  >
                    <FileDown className="w-5 h-5" />
                    Export PDF
                  </button>
                  <button
                    type="button"
                    onClick={exportExcel}
                    disabled={exporting}
                    className="flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white disabled:opacity-50"
                  >
                    <FileSpreadsheet className="w-5 h-5" />
                    Export Excel
                  </button>
                </div>
                <p className="text-xs text-slate-500 mt-2">
                  Exports all vehicles matching current filters. PDF includes header with date & time.
                </p>
              </div>
            </div>

            <div className="p-4 border-t border-slate-700">
              <button
                type="button"
                onClick={applyFilters}
                className="w-full py-3 rounded-xl bg-orange-500 hover:bg-orange-600 text-white font-medium"
              >
                Apply Filters
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
